package com.fortuneandfavors.menu;

import com.fortuneandfavors.ModItems;
import com.fortuneandfavors.ModSounds;
import com.fortuneandfavors.economy.BlockValues;
import com.fortuneandfavors.economy.ClaimManager;
import com.fortuneandfavors.economy.EconomyManager;
import com.fortuneandfavors.economy.SkillManager;
import com.fortuneandfavors.economy.SpawnerManager;
import com.fortuneandfavors.economy.SpawnerManager.SpawnerRec;
import com.fortuneandfavors.util.Chat;
import com.fortuneandfavors.util.InventoryHelper;
import com.fortuneandfavors.util.SoundUtil;
import java.util.List;
import java.util.UUID;
import net.minecraft.core.BlockPos;
import net.minecraft.core.component.DataComponents;
import net.minecraft.network.HashedStack;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.SimpleContainer;
import net.minecraft.world.SimpleMenuProvider;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.ChestMenu;
import net.minecraft.world.inventory.ContainerInput;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.component.ItemLore;
import net.minecraft.world.level.Level;

public class SpawnerMenu extends ChestMenu {
   private static final int BUFFER_START = 0;
   private static final int BUFFER_SLOTS = 18;
   private static final int SELL_ALL = 18;
   private static final int MODE_BUTTON = 22;
   private static final int INFO = 24;
   private static final int CLOSE = 26;
   private final SimpleContainer container;
   private final BlockPos pos;
   private final UUID owner;
   private final ServerPlayer ownerPlayer;

   public SpawnerMenu(int syncId, Inventory playerInventory, BlockPos pos) {
      this(syncId, playerInventory, pos, new SimpleContainer(27));
   }

   private SpawnerMenu(int syncId, Inventory playerInventory, BlockPos pos, SimpleContainer container) {
      super(MenuType.GENERIC_9x3, syncId, playerInventory, container, 3);
      this.container = container;
      this.pos = pos;
      SpawnerRec rec = SpawnerManager.get(playerInventory.player.level(), pos);
      this.owner = rec == null ? null : rec.owner();
      this.ownerPlayer = playerInventory.player instanceof ServerPlayer sp ? sp : null;
      this.rebuild();
   }

   public static void open(ServerPlayer player, BlockPos pos) {
      player.openMenu(new SimpleMenuProvider((syncId, inv, p) -> new SpawnerMenu(syncId, inv, pos), Component.literal("§5§lSpawner")));
   }

   private void rebuild() {
      this.container.clearContent();
      Level level = this.ownerPlayer.level();
      SpawnerRec rec = SpawnerManager.get(level, this.pos);
      if (rec == null) {
         this.container.setItem(24, this.info(new ItemStack(Items.SPAWNER), "§7Wild spawner", "§7Not owned - mine it to pick it up."));
         this.container.setItem(26, this.info(new ItemStack(Items.BARRIER), "§cClose", ""));
         this.broadcastChanges();
      } else {
         List<ItemStack> buffer = SpawnerManager.bufferOf(level, this.pos);

         for (int i = 0; i < 18; i++) {
            if (i < buffer.size()) {
               ItemStack s = buffer.get(i).copy();
               int lvl = ModItems.spawnerLootLevel(s);
               int pct = Math.round((1.3F + 0.15F * (lvl - 1) - 1.0F) * 100.0F);
               s.set(
                  DataComponents.LORE,
                  new ItemLore(List.of(Component.literal("§7Click to take"), Component.literal("§7Generated by this spawner · §a+" + pct + "% sell")))
               );
               this.container.setItem(0 + i, s);
            } else {
               this.container.setItem(0 + i, ItemStack.EMPTY);
            }
         }

         boolean items = rec.mode() == 1;
         if (items) {
            long total = 0L;

            for (ItemStack s : buffer) {
               total += BlockValues.valueOf(s);
            }

            this.container
               .setItem(
                  18,
                  this.info(
                     new ItemStack(Items.GOLD_INGOT), "§6§lSELL ALL", "§7Instantly sells everything inside for\n§a$" + total, "§8Boosted value · owner only"
                  )
               );
         } else {
            this.container.setItem(18, ItemStack.EMPTY);
         }

         boolean isOwner = this.owner != null && this.owner.equals(this.ownerPlayer.getUUID());
         ItemStack modeIcon = new ItemStack(items ? Items.HOPPER : Items.ZOMBIE_SPAWN_EGG);
         this.container
            .setItem(
               22,
               this.info(
                  modeIcon,
                  items ? "§a§lMODE: ITEM GAIN" : "§6§lMODE: NORMAL SPAWN",
                  items ? "§7Spawns nothing - generates the mob's drops inside" : "§7Spawns its mob like a normal spawner",
                  "§8" + (isOwner ? "Click to switch mode" : "Only the owner can switch mode")
               )
            );
         this.container
            .setItem(
               24,
               this.info(
                  new ItemStack(Items.SPAWNER),
                  "§f" + SpawnerManager.mobName(rec.type()),
                  "§7Owned by §f" + (rec.ownerName().isEmpty() ? "someone" : rec.ownerName()),
                  "§7Level: §" + (rec.level() > 1 ? "a" + rec.level() + " §7(fused - faster + more)" : "f1"),
                  "§7Mode: §" + (items ? "aItem gain" : "6Normal spawn"),
                  items ? "§7Generated items: §f" + this.bufferCount(buffer) : ""
               )
            );
         this.container.setItem(26, this.info(new ItemStack(Items.BARRIER), "§cClose", ""));
         this.broadcastChanges();
      }
   }

   private int bufferCount(List<ItemStack> buffer) {
      int n = 0;

      for (ItemStack s : buffer) {
         n += s.getCount();
      }

      return n;
   }

   private ItemStack info(ItemStack base, String name, String... lines) {
      ItemStack stack = base.copy();
      stack.set(DataComponents.CUSTOM_NAME, Component.literal(name));
      stack.set(DataComponents.LORE, new ItemLore(List.of(Component.literal(String.join("\n", lines)))));
      return stack;
   }

   private void returnCarried(ServerPlayer player) {
      ItemStack carried = this.getCarried();
      if (!carried.isEmpty()) {
         this.setCarried(ItemStack.EMPTY);
         this.setRemoteCarried(HashedStack.EMPTY);
         InventoryHelper.giveOrDrop(player, carried);
      }
   }

   public void clicked(int slotId, int button, ContainerInput input, Player player) {
      if (player instanceof ServerPlayer sp) {
         if (slotId == 26) {
            this.returnCarried(sp);
            sp.closeContainer();
         } else if (slotId >= 0 && slotId < 18) {
            if (input == ContainerInput.PICKUP || input == ContainerInput.QUICK_MOVE) {
               this.takeDrop(sp, slotId - 0);
            }

            this.returnCarried(sp);
         } else if (slotId == 22) {
            if (input == ContainerInput.PICKUP || input == ContainerInput.QUICK_MOVE) {
               this.toggleMode(sp);
            }

            this.returnCarried(sp);
         } else if (slotId != 18) {
            if (slotId >= 0 && slotId < 27) {
               this.returnCarried(sp);
            } else {
               super.clicked(slotId, button, input, player);
            }
         } else {
            if (input == ContainerInput.PICKUP || input == ContainerInput.QUICK_MOVE) {
               this.sellAll(sp);
            }

            this.returnCarried(sp);
         }
      } else {
         super.clicked(slotId, button, input, player);
      }
   }

   private void sellAll(ServerPlayer player) {
      Level level = player.level();
      SpawnerRec rec = SpawnerManager.get(level, this.pos);
      if (rec != null) {
         if ((rec.owner() == null || !rec.owner().equals(player.getUUID())) && !ClaimManager.isAdminOp(player)) {
            Chat.msg(player, "&cOnly the owner can sell this spawner's loot.");
         } else {
            List<ItemStack> items = SpawnerManager.drainBuffer(level, this.pos);
            if (items.isEmpty()) {
               SoundUtil.play(player, ModSounds.DENY);
               Chat.msg(player, "&7The spawner has nothing to sell.");
               this.rebuild();
            } else {
               float mult = SkillManager.sellMultiplier(player.getUUID());
               long total = 0L;

               for (ItemStack s : items) {
                  total += Math.round((float)BlockValues.valueOf(s) * mult);
               }

               EconomyManager.addCash(player.getUUID(), total);
               SoundUtil.play(player, ModSounds.SELL);
               Chat.raw(player, "&aSold the spawner's loot for " + Chat.moneyStr(total) + "&a!");
               this.rebuild();
            }
         }
      }
   }

   private void takeDrop(ServerPlayer player, int index) {
      Level level = player.level();
      if (!ClaimManager.canOpenChest(player, this.pos) && !SpawnerManager.canBreak(level, this.pos, player)) {
         Chat.msg(player, "&cThis land is claimed - you can't take from this spawner.");
      } else {
         ItemStack taken = SpawnerManager.takeDrop(level, this.pos, index);
         if (!taken.isEmpty()) {
            InventoryHelper.giveOrDrop(player, taken);
            SoundUtil.play(player, ModSounds.SELL);
            this.rebuild();
         }
      }
   }

   private void toggleMode(ServerPlayer player) {
      Level level = player.level();
      SpawnerRec rec = SpawnerManager.get(level, this.pos);
      if (rec != null) {
         if ((rec.owner() == null || !rec.owner().equals(player.getUUID())) && !ClaimManager.isAdminOp(player)) {
            Chat.msg(player, "&cOnly the owner can switch this spawner's mode.");
         } else {
            int mode = rec.mode() == 1 ? 0 : 1;
            SpawnerManager.setMode(level, this.pos, mode);
            Chat.raw(player, "&aSpawner is now in " + (mode == 1 ? "&eITEM GAIN&a mode - it generates drops." : "&6NORMAL&a mode - it spawns mobs."));
            SoundUtil.play(player, ModSounds.TRANSFER);
            this.rebuild();
         }
      }
   }

   public ItemStack quickMoveStack(Player player, int index) {
      if (index >= 0 && index < 18 && player instanceof ServerPlayer sp) {
         this.clicked(index, 0, ContainerInput.QUICK_MOVE, sp);
      }

      return ItemStack.EMPTY;
   }
}
